"""
Core Configuration for the Drug Screening Pipeline

This file contains settings essential for the execution of the
compound screening workflow, including docking, simulation, and analysis.

It is kept separate from the main config.py to ensure the screening
pipeline is independent of knowledge-base or AI generation configurations
like LLMs and Neo4j.
"""

import os
from dotenv import load_dotenv

# Load environment variables from a .env file if it exists
load_dotenv()

# --- Core Data and Output Paths ---
DATA_PATH = "data/"
OUTPUTS_PATH = "outputs/"
DOCKING_OUTPUT_PATH = os.path.join(OUTPUTS_PATH, "docking")
MD_OUTPUT_PATH = os.path.join(OUTPUTS_PATH, "md")
REPORTS_OUTPUT_PATH = os.path.join(OUTPUTS_PATH, "reports")


# --- Pocket2Mol Configuration ---
# Path to the cloned Pocket2Mol repository
POCKET2MOL_PATH = os.getenv("POCKET2MOL_PATH", "external_tools/Pocket2Mol")
# Name of the conda environment created for Pocket2Mol
POCKET2MOL_ENV_NAME = os.getenv("POCKET2MOL_ENV_NAME", "Pocket2Mol")
# Directory to save molecules generated by Pocket2Mol
POCKET2MOL_OUTPUT_PATH = os.path.join(OUTPUTS_PATH, "pocket2mol_generations")


# --- External Tool Paths for In-Silico Simulation ---

# Path to the AutoDock Vina executable
AUTODOCK_VINA_BIN: str | None = os.getenv("AUTODOCK_VINA_BIN", "vina")

# Path to the fpocket executable for binding pocket detection
FPOCKET_BIN: str | None = os.getenv("FPOCKET_BIN", "fpocket")

# (Optional) GROMACS settings for Molecular Dynamics
GROMACS_BIN: str | None = os.getenv("GROMACS_BIN", "gmx")

# (Optional) OpenMM settings for Molecular Dynamics
OPENMM_PLATFORM: str | None = os.getenv("OPENMM_PLATFORM", "CUDA")

# (Optional) MM/GBSA script path for binding free energy calculation
MMGBSA_SCRIPT: str | None = os.getenv("MMGBSA_SCRIPT", "MMPBSA.py")

# Create output directories if they don't exist
os.makedirs(DOCKING_OUTPUT_PATH, exist_ok=True)
os.makedirs(MD_OUTPUT_PATH, exist_ok=True)
os.makedirs(REPORTS_OUTPUT_PATH, exist_ok=True)
os.makedirs(POCKET2MOL_OUTPUT_PATH, exist_ok=True) 